//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EulerFinancial.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EulerFinancial.Resources.ExceptionString", typeof(ExceptionString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A search expression could not be built from the given parameters..
        /// </summary>
        internal static string Search_General_Invalid {
            get {
                return ResourceManager.GetString("Search.General.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; could not be found for type &apos;{1}&apos;..
        /// </summary>
        internal static string Search_ParameterNotValidForType {
            get {
                return ResourceManager.GetString("Search.ParameterNotValidForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query string &apos;{0}&apos; could not be parsed..
        /// </summary>
        internal static string Search_Parse {
            get {
                return ResourceManager.GetString("Search.Parse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be a date..
        /// </summary>
        internal static string Validation_Date_General {
            get {
                return ResourceManager.GetString("Validation.Date.General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be a date on or after {1}..
        /// </summary>
        internal static string Validation_Date_MustBeOnOrAfter {
            get {
                return ResourceManager.GetString("Validation.Date.MustBeOnOrAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be a date between {1} and {2}..
        /// </summary>
        internal static string Validation_Date_MustBeWithinRange {
            get {
                return ResourceManager.GetString("Validation.Date.MustBeWithinRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be a date on or before {1}..
        /// </summary>
        internal static string Validation_Date_MustOnOrBeBefore {
            get {
                return ResourceManager.GetString("Validation.Date.MustOnOrBeBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} could not be validated..
        /// </summary>
        internal static string Validation_General_Model {
            get {
                return ResourceManager.GetString("Validation.General.Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; could not be validated..
        /// </summary>
        internal static string Validation_General_Value {
            get {
                return ResourceManager.GetString("Validation.General.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be a number greater than {1}..
        /// </summary>
        internal static string Validation_Number_MustBeGreaterThan {
            get {
                return ResourceManager.GetString("Validation.Number.MustBeGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be a number greater than or equal to {1}..
        /// </summary>
        internal static string Validation_Number_MustBeGreaterThanOrEqual {
            get {
                return ResourceManager.GetString("Validation.Number.MustBeGreaterThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be a number less than {1}..
        /// </summary>
        internal static string Validation_Number_MustBeLessThan {
            get {
                return ResourceManager.GetString("Validation.Number.MustBeLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be a number less than or equal to {1}..
        /// </summary>
        internal static string Validation_Number_MustBeLessThanOrEqual {
            get {
                return ResourceManager.GetString("Validation.Number.MustBeLessThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be a number between {1} and {2}..
        /// </summary>
        internal static string Validation_Number_MustBeWithinRange {
            get {
                return ResourceManager.GetString("Validation.Number.MustBeWithinRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One search field must be selected..
        /// </summary>
        internal static string Validation_SearchMember_IsNull {
            get {
                return ResourceManager.GetString("Validation.SearchMember.IsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol is missing defintion for selected type..
        /// </summary>
        internal static string Validation_SecuritySymbol_IncorrectType {
            get {
                return ResourceManager.GetString("Validation.SecuritySymbol.IncorrectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective date must be less than or equal to expiration date..
        /// </summary>
        internal static string Validation_SecuritySymbol_InvalidDateRange {
            get {
                return ResourceManager.GetString("Validation.SecuritySymbol.InvalidDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books are closed. Only transactions after the books closed date may be modified..
        /// </summary>
        internal static string Validation_Transaction_BooksClosed {
            get {
                return ResourceManager.GetString("Validation.Transaction.BooksClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML input could not be validated. Verify the provided elements and attributes are supported..
        /// </summary>
        internal static string Validation_Xml_General {
            get {
                return ResourceManager.GetString("Validation.Xml.General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The schema &apos;{0}&apos; does not match the expected value. The file may have been altered..
        /// </summary>
        internal static string Validation_Xml_SchemaMismatch {
            get {
                return ResourceManager.GetString("Validation.Xml.SchemaMismatch", resourceCulture);
            }
        }
    }
}
