//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EulerFinancial.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelDisplayName {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelDisplayName() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EulerFinancial.Resources.ModelDisplayName", typeof(ModelDisplayName).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custodian.
        /// </summary>
        public static string Account_AccountCustodianId {
            get {
                return ResourceManager.GetString("Account.AccountCustodianId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acct. #.
        /// </summary>
        public static string Account_AccountNumber {
            get {
                return ResourceManager.GetString("Account.AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books Closed.
        /// </summary>
        public static string Account_BooksClosedDate {
            get {
                return ResourceManager.GetString("Account.BooksClosedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Order.
        /// </summary>
        public static string Account_DisplayOrder {
            get {
                return ResourceManager.GetString("Account.DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Bank.
        /// </summary>
        public static string Account_HasBankTransaction {
            get {
                return ResourceManager.GetString("Account.HasBankTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Broker.
        /// </summary>
        public static string Account_HasBrokerTransaction {
            get {
                return ResourceManager.GetString("Account.HasBrokerTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Wallet.
        /// </summary>
        public static string Account_HasWallet {
            get {
                return ResourceManager.GetString("Account.HasWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tradable.
        /// </summary>
        public static string Account_IsComplianceTradable {
            get {
                return ResourceManager.GetString("Account.IsComplianceTradable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account / Group.
        /// </summary>
        public static string AccountAttributeMemberEntry_AccountObjectId {
            get {
                return ResourceManager.GetString("AccountAttributeMemberEntry.AccountObjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string AccountAttributeMemberEntry_AttributeMemberId {
            get {
                return ResourceManager.GetString("AccountAttributeMemberEntry.AttributeMemberId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Date.
        /// </summary>
        public static string AccountAttributeMemberEntry_EffectiveDate {
            get {
                return ResourceManager.GetString("AccountAttributeMemberEntry.EffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string AccountAttributeMemberEntry_Weight {
            get {
                return ResourceManager.GetString("AccountAttributeMemberEntry.Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string AccountCustodian_CustodianCode {
            get {
                return ResourceManager.GetString("AccountCustodian.CustodianCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string AccountCustodian_DisplayName {
            get {
                return ResourceManager.GetString("AccountCustodian.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Order.
        /// </summary>
        public static string AccountGroup_DisplayOrder {
            get {
                return ResourceManager.GetString("AccountGroup.DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string AccountGroupMember_AccountGroupId {
            get {
                return ResourceManager.GetString("AccountGroupMember.AccountGroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string AccountGroupMember_AccountId {
            get {
                return ResourceManager.GetString("AccountGroupMember.AccountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Date.
        /// </summary>
        public static string AccountGroupMember_EntryDate {
            get {
                return ResourceManager.GetString("AccountGroupMember.EntryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit date.
        /// </summary>
        public static string AccountGroupMember_ExitDate {
            get {
                return ResourceManager.GetString("AccountGroupMember.ExitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string AccountObject_AccountObjectCode {
            get {
                return ResourceManager.GetString("AccountObject.AccountObjectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Date.
        /// </summary>
        public static string AccountObject_CloseDate {
            get {
                return ResourceManager.GetString("AccountObject.CloseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string AccountObject_ObjectDescription {
            get {
                return ResourceManager.GetString("AccountObject.ObjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AccountObject_ObjectDisplayName {
            get {
                return ResourceManager.GetString("AccountObject.ObjectDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string AccountObject_ObjectType {
            get {
                return ResourceManager.GetString("AccountObject.ObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Code.
        /// </summary>
        public static string AccountObject_PrefixedObjectCode {
            get {
                return ResourceManager.GetString("AccountObject.PrefixedObjectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string AccountObject_StartDate {
            get {
                return ResourceManager.GetString("AccountObject.StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string AccountWallet_AccountID {
            get {
                return ResourceManager.GetString("AccountWallet.AccountID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string AccountWallet_AddressCode {
            get {
                return ResourceManager.GetString("AccountWallet.AddressCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string AccountWallet_AddressTag {
            get {
                return ResourceManager.GetString("AccountWallet.AddressTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denomination.
        /// </summary>
        public static string AccountWallet_DenominationSecurityId {
            get {
                return ResourceManager.GetString("AccountWallet.DenominationSecurityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string BankTransaction_AccountId {
            get {
                return ResourceManager.GetString("BankTransaction.AccountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string BankTransaction_Amount {
            get {
                return ResourceManager.GetString("BankTransaction.Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string BankTransaction_Comment {
            get {
                return ResourceManager.GetString("BankTransaction.Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Code.
        /// </summary>
        public static string BankTransaction_TransactionCodeId {
            get {
                return ResourceManager.GetString("BankTransaction.TransactionCodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string BankTransaction_TransactionDate {
            get {
                return ResourceManager.GetString("BankTransaction.TransactionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string BankTransactionCode_DisplayName {
            get {
                return ResourceManager.GetString("BankTransactionCode.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string BankTransactionCode_TransactionCode {
            get {
                return ResourceManager.GetString("BankTransactionCode.TransactionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Transaction Code.
        /// </summary>
        public static string BankTransactionCode_TransactionCodeId {
            get {
                return ResourceManager.GetString("BankTransactionCode.TransactionCodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Member.
        /// </summary>
        public static string BankTransactionCodeAttributeMemberEntry_AttributeMemberId {
            get {
                return ResourceManager.GetString("BankTransactionCodeAttributeMemberEntry.AttributeMemberId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Date.
        /// </summary>
        public static string BankTransactionCodeAttributeMemberEntry_EffectiveDate {
            get {
                return ResourceManager.GetString("BankTransactionCodeAttributeMemberEntry.EffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Code.
        /// </summary>
        public static string BankTransactionCodeAttributeMemberEntry_TransactionCodeId {
            get {
                return ResourceManager.GetString("BankTransactionCodeAttributeMemberEntry.TransactionCodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string BankTransactionCodeAttributeMemberEntry_Weight {
            get {
                return ResourceManager.GetString("BankTransactionCodeAttributeMemberEntry.Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string BrokerTransaction_AccountID {
            get {
                return ResourceManager.GetString("BrokerTransaction.AccountID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acq. Date.
        /// </summary>
        public static string BrokerTransaction_AcquisitionDate {
            get {
                return ResourceManager.GetString("BrokerTransaction.AcquisitionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string BrokerTransaction_Amount {
            get {
                return ResourceManager.GetString("BrokerTransaction.Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dep. Security.
        /// </summary>
        public static string BrokerTransaction_DepSecurityId {
            get {
                return ResourceManager.GetString("BrokerTransaction.DepSecurityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee.
        /// </summary>
        public static string BrokerTransaction_Fee {
            get {
                return ResourceManager.GetString("BrokerTransaction.Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string BrokerTransaction_Quantity {
            get {
                return ResourceManager.GetString("BrokerTransaction.Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string BrokerTransaction_SecurityId {
            get {
                return ResourceManager.GetString("BrokerTransaction.SecurityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settle Date.
        /// </summary>
        public static string BrokerTransaction_SettleDate {
            get {
                return ResourceManager.GetString("BrokerTransaction.SettleDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Lot.
        /// </summary>
        public static string BrokerTransaction_TaxLotID {
            get {
                return ResourceManager.GetString("BrokerTransaction.TaxLotID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Date.
        /// </summary>
        public static string BrokerTransaction_TradeDate {
            get {
                return ResourceManager.GetString("BrokerTransaction.TradeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string BrokerTransaction_TransactionCodeId {
            get {
                return ResourceManager.GetString("BrokerTransaction.TransactionCodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withholding.
        /// </summary>
        public static string BrokerTransaction_Withholding {
            get {
                return ResourceManager.GetString("BrokerTransaction.Withholding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Effect.
        /// </summary>
        public static string BrokerTransactionCode_CashEffect {
            get {
                return ResourceManager.GetString("BrokerTransactionCode.CashEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contribution Effect.
        /// </summary>
        public static string BrokerTransactionCode_ContributionWithdrawalEffect {
            get {
                return ResourceManager.GetString("BrokerTransactionCode.ContributionWithdrawalEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string BrokerTransactionCode_DisplayName {
            get {
                return ResourceManager.GetString("BrokerTransactionCode.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Effect.
        /// </summary>
        public static string BrokerTransactionCode_QuantityEffect {
            get {
                return ResourceManager.GetString("BrokerTransactionCode.QuantityEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string BrokerTransactionCode_TransactionCode {
            get {
                return ResourceManager.GetString("BrokerTransactionCode.TransactionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Member.
        /// </summary>
        public static string BrokerTransactionCodeAttributeMemberEntry_AttributeMemberId {
            get {
                return ResourceManager.GetString("BrokerTransactionCodeAttributeMemberEntry.AttributeMemberId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Date.
        /// </summary>
        public static string BrokerTransactionCodeAttributeMemberEntry_EffectiveDate {
            get {
                return ResourceManager.GetString("BrokerTransactionCodeAttributeMemberEntry.EffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string BrokerTransactionCodeAttributeMemberEntry_TransactionCodeId {
            get {
                return ResourceManager.GetString("BrokerTransactionCodeAttributeMemberEntry.TransactionCodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string BrokerTransactionCodeAttributeMemberEntry_Weight {
            get {
                return ResourceManager.GetString("BrokerTransactionCodeAttributeMemberEntry.Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string Country_DisplayName {
            get {
                return ResourceManager.GetString("Country.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO-3 Code.
        /// </summary>
        public static string Country_IsoCode3 {
            get {
                return ResourceManager.GetString("Country.IsoCode3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Member.
        /// </summary>
        public static string CountryAttributeMemberEntry_AttributeMemberId {
            get {
                return ResourceManager.GetString("CountryAttributeMemberEntry.AttributeMemberId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string CountryAttributeMemberEntry_CountryID {
            get {
                return ResourceManager.GetString("CountryAttributeMemberEntry.CountryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Date.
        /// </summary>
        public static string CountryAttributeMemberEntry_EffectiveDate {
            get {
                return ResourceManager.GetString("CountryAttributeMemberEntry.EffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string CountryAttributeMemberEntry_Weight {
            get {
                return ResourceManager.GetString("CountryAttributeMemberEntry.Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account / Group.
        /// </summary>
        public static string InvestmentPerformanceAttributeMemberEntry_AccountObjectID {
            get {
                return ResourceManager.GetString("InvestmentPerformanceAttributeMemberEntry.AccountObjectID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Member.
        /// </summary>
        public static string InvestmentPerformanceAttributeMemberEntry_AttributeMemberID {
            get {
                return ResourceManager.GetString("InvestmentPerformanceAttributeMemberEntry.AttributeMemberID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Capital.
        /// </summary>
        public static string InvestmentPerformanceAttributeMemberEntry_AverageCapital {
            get {
                return ResourceManager.GetString("InvestmentPerformanceAttributeMemberEntry.AverageCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        public static string InvestmentPerformanceAttributeMemberEntry_FromDate {
            get {
                return ResourceManager.GetString("InvestmentPerformanceAttributeMemberEntry.FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain.
        /// </summary>
        public static string InvestmentPerformanceAttributeMemberEntry_Gain {
            get {
                return ResourceManager.GetString("InvestmentPerformanceAttributeMemberEntry.Gain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRR.
        /// </summary>
        public static string InvestmentPerformanceAttributeMemberEntry_IRR {
            get {
                return ResourceManager.GetString("InvestmentPerformanceAttributeMemberEntry.IRR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Value.
        /// </summary>
        public static string InvestmentPerformanceAttributeMemberEntry_MarketValue {
            get {
                return ResourceManager.GetString("InvestmentPerformanceAttributeMemberEntry.MarketValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Contribution.
        /// </summary>
        public static string InvestmentPerformanceAttributeMemberEntry_NetContribution {
            get {
                return ResourceManager.GetString("InvestmentPerformanceAttributeMemberEntry.NetContribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        public static string InvestmentPerformanceAttributeMemberEntry_ToDate {
            get {
                return ResourceManager.GetString("InvestmentPerformanceAttributeMemberEntry.ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account / Group.
        /// </summary>
        public static string InvestmentPerformanceEntry_AccountObjectID {
            get {
                return ResourceManager.GetString("InvestmentPerformanceEntry.AccountObjectID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Capital.
        /// </summary>
        public static string InvestmentPerformanceEntry_AverageCapital {
            get {
                return ResourceManager.GetString("InvestmentPerformanceEntry.AverageCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        public static string InvestmentPerformanceEntry_FromDate {
            get {
                return ResourceManager.GetString("InvestmentPerformanceEntry.FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain.
        /// </summary>
        public static string InvestmentPerformanceEntry_Gain {
            get {
                return ResourceManager.GetString("InvestmentPerformanceEntry.Gain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRR.
        /// </summary>
        public static string InvestmentPerformanceEntry_IRR {
            get {
                return ResourceManager.GetString("InvestmentPerformanceEntry.IRR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Value.
        /// </summary>
        public static string InvestmentPerformanceEntry_MarketValue {
            get {
                return ResourceManager.GetString("InvestmentPerformanceEntry.MarketValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Contribution.
        /// </summary>
        public static string InvestmentPerformanceEntry_NetContribution {
            get {
                return ResourceManager.GetString("InvestmentPerformanceEntry.NetContribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        public static string InvestmentPerformanceEntry_ToDate {
            get {
                return ResourceManager.GetString("InvestmentPerformanceEntry.ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string InvestmentStrategy_DisplayName {
            get {
                return ResourceManager.GetString("InvestmentStrategy.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Member.
        /// </summary>
        public static string InvestmentStrategyTarget_AttributeMemberID {
            get {
                return ResourceManager.GetString("InvestmentStrategyTarget.AttributeMemberID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Date.
        /// </summary>
        public static string InvestmentStrategyTarget_EffectiveDate {
            get {
                return ResourceManager.GetString("InvestmentStrategyTarget.EffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy.
        /// </summary>
        public static string InvestmentStrategyTarget_InvestmentStrategyID {
            get {
                return ResourceManager.GetString("InvestmentStrategyTarget.InvestmentStrategyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string InvestmentStrategyTarget_TargetPercent {
            get {
                return ResourceManager.GetString("InvestmentStrategyTarget.TargetPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string MarketHoliday_MarketHolidayName {
            get {
                return ResourceManager.GetString("MarketHoliday.MarketHolidayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday.
        /// </summary>
        public static string MarketHolidaySchedule_MarketHolidayID {
            get {
                return ResourceManager.GetString("MarketHolidaySchedule.MarketHolidayID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observance Date.
        /// </summary>
        public static string MarketHolidaySchedule_ObservanceDate {
            get {
                return ResourceManager.GetString("MarketHolidaySchedule.ObservanceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string MarketIndex_IndexCode {
            get {
                return ResourceManager.GetString("MarketIndex.IndexCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string MarketIndex_IndexDescription {
            get {
                return ResourceManager.GetString("MarketIndex.IndexDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string MarketIndexPrice_MarketIndexID {
            get {
                return ResourceManager.GetString("MarketIndexPrice.MarketIndexID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string MarketIndexPrice_Price {
            get {
                return ResourceManager.GetString("MarketIndexPrice.Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Type.
        /// </summary>
        public static string MarketIndexPrice_PriceCode {
            get {
                return ResourceManager.GetString("MarketIndexPrice.PriceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string MarketIndexPrice_PriceDate {
            get {
                return ResourceManager.GetString("MarketIndexPrice.PriceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string ModelAttribute_DisplayName {
            get {
                return ResourceManager.GetString("ModelAttribute.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        public static string ModelAttributeMember_AttributeID {
            get {
                return ResourceManager.GetString("ModelAttributeMember.AttributeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string ModelAttributeMember_DisplayName {
            get {
                return ResourceManager.GetString("ModelAttributeMember.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Order.
        /// </summary>
        public static string ModelAttributeMember_DisplayOrder {
            get {
                return ResourceManager.GetString("ModelAttributeMember.DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        public static string ModelAttributeScope_AttributeID {
            get {
                return ResourceManager.GetString("ModelAttributeScope.AttributeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope Code.
        /// </summary>
        public static string ModelAttributeScope_ScopeCode {
            get {
                return ResourceManager.GetString("ModelAttributeScope.ScopeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string ReportConfiguration_ConfigurationCode {
            get {
                return ResourceManager.GetString("ReportConfiguration.ConfigurationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ReportConfiguration_ConfigurationDescription {
            get {
                return ResourceManager.GetString("ReportConfiguration.ConfigurationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Definition.
        /// </summary>
        public static string ReportConfiguration_XmlDefinition {
            get {
                return ResourceManager.GetString("ReportConfiguration.XmlDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string ReportStyleSheet_StyleSheetCode {
            get {
                return ResourceManager.GetString("ReportStyleSheet.StyleSheetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ReportStyleSheet_StyleSheetDescription {
            get {
                return ResourceManager.GetString("ReportStyleSheet.StyleSheetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Definition.
        /// </summary>
        public static string ReportStyleSheet_XmlDefinition {
            get {
                return ResourceManager.GetString("ReportStyleSheet.XmlDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Extension.
        /// </summary>
        public static string ResourceImage_FileExtension {
            get {
                return ResourceManager.GetString("ResourceImage.FileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ResourceImage_ImageDescription {
            get {
                return ResourceManager.GetString("ResourceImage.ImageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        public static string Security_CurrentSymbol {
            get {
                return ResourceManager.GetString("Security.CurrentSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perpetual Market.
        /// </summary>
        public static string Security_HasPerpetualMarket {
            get {
                return ResourceManager.GetString("Security.HasPerpetualMarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perpetual Price.
        /// </summary>
        public static string Security_HasPerpetualPrice {
            get {
                return ResourceManager.GetString("Security.HasPerpetualPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer.
        /// </summary>
        public static string Security_Issuer {
            get {
                return ResourceManager.GetString("Security.Issuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Security_SecurityDescription {
            get {
                return ResourceManager.GetString("Security.SecurityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange.
        /// </summary>
        public static string Security_SecurityExchangeID {
            get {
                return ResourceManager.GetString("Security.SecurityExchangeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sec. Type.
        /// </summary>
        public static string Security_SecurityTypeID {
            get {
                return ResourceManager.GetString("Security.SecurityTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Member.
        /// </summary>
        public static string SecurityAttributeMemberEntry_AttributeMemberID {
            get {
                return ResourceManager.GetString("SecurityAttributeMemberEntry.AttributeMemberID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Date.
        /// </summary>
        public static string SecurityAttributeMemberEntry_EffectiveDate {
            get {
                return ResourceManager.GetString("SecurityAttributeMemberEntry.EffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string SecurityAttributeMemberEntry_SecurityID {
            get {
                return ResourceManager.GetString("SecurityAttributeMemberEntry.SecurityID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string SecurityAttributeMemberEntry_Weight {
            get {
                return ResourceManager.GetString("SecurityAttributeMemberEntry.Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string SecurityExchange_ExchangeCode {
            get {
                return ResourceManager.GetString("SecurityExchange.ExchangeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string SecurityExchange_ExchangeDescription {
            get {
                return ResourceManager.GetString("SecurityExchange.ExchangeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string SecurityPrice_PriceClose {
            get {
                return ResourceManager.GetString("SecurityPrice.PriceClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string SecurityPrice_PriceDate {
            get {
                return ResourceManager.GetString("SecurityPrice.PriceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string SecurityPrice_PriceHigh {
            get {
                return ResourceManager.GetString("SecurityPrice.PriceHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string SecurityPrice_PriceLow {
            get {
                return ResourceManager.GetString("SecurityPrice.PriceLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string SecurityPrice_PriceOpen {
            get {
                return ResourceManager.GetString("SecurityPrice.PriceOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string SecurityPrice_SecurityID {
            get {
                return ResourceManager.GetString("SecurityPrice.SecurityID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string SecurityPrice_Volume {
            get {
                return ResourceManager.GetString("SecurityPrice.Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUSIP.
        /// </summary>
        public static string SecuritySymbol_Cusip {
            get {
                return ResourceManager.GetString("SecuritySymbol.Cusip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Symbol.
        /// </summary>
        public static string SecuritySymbol_CustomSymbol {
            get {
                return ResourceManager.GetString("SecuritySymbol.CustomSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Date.
        /// </summary>
        public static string SecuritySymbol_EffectiveDate {
            get {
                return ResourceManager.GetString("SecuritySymbol.EffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option Ticker.
        /// </summary>
        public static string SecuritySymbol_OptionTicker {
            get {
                return ResourceManager.GetString("SecuritySymbol.OptionTicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string SecuritySymbol_SecurityID {
            get {
                return ResourceManager.GetString("SecuritySymbol.SecurityID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string SecuritySymbol_SymbolTypeID {
            get {
                return ResourceManager.GetString("SecuritySymbol.SymbolTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticker.
        /// </summary>
        public static string SecuritySymbol_Ticker {
            get {
                return ResourceManager.GetString("SecuritySymbol.Ticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custodian.
        /// </summary>
        public static string SecuritySymbolMap_AccountCustodianID {
            get {
                return ResourceManager.GetString("SecuritySymbolMap.AccountCustodianID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol (Custodian).
        /// </summary>
        public static string SecuritySymbolMap_CustodianSymbol {
            get {
                return ResourceManager.GetString("SecuritySymbolMap.CustodianSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol (Application).
        /// </summary>
        public static string SecuritySymbolMap_SecuritySymbolID {
            get {
                return ResourceManager.GetString("SecuritySymbolMap.SecuritySymbolID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Name.
        /// </summary>
        public static string SecuritySymbolType_SymbolTypeName {
            get {
                return ResourceManager.GetString("SecuritySymbolType.SymbolTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Derivatives.
        /// </summary>
        public static string SecurityType_CanHaveDerivative {
            get {
                return ResourceManager.GetString("SecurityType.CanHaveDerivative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Positions.
        /// </summary>
        public static string SecurityType_CanHavePosition {
            get {
                return ResourceManager.GetString("SecurityType.CanHavePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Order.
        /// </summary>
        public static string SecurityType_DisplayOrder {
            get {
                return ResourceManager.GetString("SecurityType.DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Group.
        /// </summary>
        public static string SecurityType_SecurityTypeGroupID {
            get {
                return ResourceManager.GetString("SecurityType.SecurityTypeGroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SecurityType_SecurityTypeName {
            get {
                return ResourceManager.GetString("SecurityType.SecurityTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valuation Factor.
        /// </summary>
        public static string SecurityType_ValuationFactor {
            get {
                return ResourceManager.GetString("SecurityType.ValuationFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Order.
        /// </summary>
        public static string SecurityTypeGroup_DisplayOrder {
            get {
                return ResourceManager.GetString("SecurityTypeGroup.DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SecurityTypeGroup_SecurityTypeGroupName {
            get {
                return ResourceManager.GetString("SecurityTypeGroup.SecurityTypeGroupName", resourceCulture);
            }
        }
    }
}
