//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EulerFinancial.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Noun {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Noun() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EulerFinancial.Resources.Noun", typeof(Noun).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (the,account):(the,accounts).
        /// </summary>
        internal static string Model_Account {
            get {
                return ResourceManager.GetString("Model.Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (the,attribute entry):(the,attribute entries).
        /// </summary>
        internal static string Model_AccountAttributeMemberEntry {
            get {
                return ResourceManager.GetString("Model.AccountAttributeMemberEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (the,custodian):;(the,custodians).
        /// </summary>
        internal static string Model_AccountCustodian {
            get {
                return ResourceManager.GetString("Model.AccountCustodian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (the,account group):(the,account groups).
        /// </summary>
        internal static string Model_AccountGroup {
            get {
                return ResourceManager.GetString("Model.AccountGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (the,member):(the,members).
        /// </summary>
        internal static string Model_AccountGroupMember {
            get {
                return ResourceManager.GetString("Model.AccountGroupMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Model_AccountObject {
            get {
                return ResourceManager.GetString("Model.AccountObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (the,wallet):(the,wallets).
        /// </summary>
        internal static string Model_AccountWallet {
            get {
                return ResourceManager.GetString("Model.AccountWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (the,audit event):(the,audit events).
        /// </summary>
        internal static string Model_AuditEvent {
            get {
                return ResourceManager.GetString("Model.AuditEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (the,transaction):(the,transactions).
        /// </summary>
        internal static string Model_BankTransaction {
            get {
                return ResourceManager.GetString("Model.BankTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (the,code):(the,codes).
        /// </summary>
        internal static string Model_BankTransactionCode {
            get {
                return ResourceManager.GetString("Model.BankTransactionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (the,attribute entry):(the,attribute entries).
        /// </summary>
        internal static string Model_BankTransactionCodeAttributeMemberEntry {
            get {
                return ResourceManager.GetString("Model.BankTransactionCodeAttributeMemberEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (the,transaction):(the,transactions).
        /// </summary>
        internal static string Model_BrokerTransaction {
            get {
                return ResourceManager.GetString("Model.BrokerTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (the,code):(the,codes).
        /// </summary>
        internal static string Model_BrokerTransactionCode {
            get {
                return ResourceManager.GetString("Model.BrokerTransactionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (the,attribute entry):(the,attribute entries).
        /// </summary>
        internal static string Model_BrokerTransactionCodeAttributeMemberEntry {
            get {
                return ResourceManager.GetString("Model.BrokerTransactionCodeAttributeMemberEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (the,tax lot):(the,tax lots).
        /// </summary>
        internal static string Model_BrokerTransactionTaxLot {
            get {
                return ResourceManager.GetString("Model.BrokerTransactionTaxLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (the,country):(the,countries).
        /// </summary>
        internal static string Model_Country {
            get {
                return ResourceManager.GetString("Model.Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (the,attribute entry):(the,attribute entries).
        /// </summary>
        internal static string Model_CountryAttributeMemberEntry {
            get {
                return ResourceManager.GetString("Model.CountryAttributeMemberEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (the,performance row):(the,performance rows).
        /// </summary>
        internal static string Model_InvestmentPerformanceAttributeMemberEntry {
            get {
                return ResourceManager.GetString("Model.InvestmentPerformanceAttributeMemberEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (the,performance row):(the,performance rows).
        /// </summary>
        internal static string Model_InvestmentPerformanceEntry {
            get {
                return ResourceManager.GetString("Model.InvestmentPerformanceEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (the,investment strategy):(the,investment strategies).
        /// </summary>
        internal static string Model_InvestmentStrategy {
            get {
                return ResourceManager.GetString("Model.InvestmentStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (the,target):(the,targets).
        /// </summary>
        internal static string Model_InvestmentStrategyTarget {
            get {
                return ResourceManager.GetString("Model.InvestmentStrategyTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (the,holiday):(the,holidays).
        /// </summary>
        internal static string Model_MarketHoliday {
            get {
                return ResourceManager.GetString("Model.MarketHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (the,holiday observance):(the,holiday observances).
        /// </summary>
        internal static string Model_MarketHolidaySchedule {
            get {
                return ResourceManager.GetString("Model.MarketHolidaySchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (the,market index):(the,market indexes).
        /// </summary>
        internal static string Model_MarketIndex {
            get {
                return ResourceManager.GetString("Model.MarketIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (the,index price):(the,index prices).
        /// </summary>
        internal static string Model_MarketIndexPrice {
            get {
                return ResourceManager.GetString("Model.MarketIndexPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (the,attribute):(the,attributes).
        /// </summary>
        internal static string Model_ModelAttribute {
            get {
                return ResourceManager.GetString("Model.ModelAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (the,attribute member):(the,attribute members).
        /// </summary>
        internal static string Model_ModelAttributeMember {
            get {
                return ResourceManager.GetString("Model.ModelAttributeMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (the,attribute scope):(the,attribute scopes).
        /// </summary>
        internal static string Model_ModelAttributeScope {
            get {
                return ResourceManager.GetString("Model.ModelAttributeScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Model_ReportConfiguration {
            get {
                return ResourceManager.GetString("Model.ReportConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Model_ReportStyleSheet {
            get {
                return ResourceManager.GetString("Model.ReportStyleSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Model_ResourceImage {
            get {
                return ResourceManager.GetString("Model.ResourceImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Model_Security {
            get {
                return ResourceManager.GetString("Model.Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (the,attribute entry):(the,attribute entries).
        /// </summary>
        internal static string Model_SecurityAttributeMemberEntry {
            get {
                return ResourceManager.GetString("Model.SecurityAttributeMemberEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Model_SecurityExchange {
            get {
                return ResourceManager.GetString("Model.SecurityExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Model_SecurityPrice {
            get {
                return ResourceManager.GetString("Model.SecurityPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Model_SecuritySymbol {
            get {
                return ResourceManager.GetString("Model.SecuritySymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Model_SecuritySymbolMap {
            get {
                return ResourceManager.GetString("Model.SecuritySymbolMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Model_SecuritySymbolType {
            get {
                return ResourceManager.GetString("Model.SecuritySymbolType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Model_SecurityType {
            get {
                return ResourceManager.GetString("Model.SecurityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Model_SecurityTypeGroup {
            get {
                return ResourceManager.GetString("Model.SecurityTypeGroup", resourceCulture);
            }
        }
    }
}
