//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NjordFinance.Model.Metadata {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CheckConstraintDisplay {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CheckConstraintDisplay() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NjordFinance.Model.Metadata.CheckConstraintDisplay", typeof(CheckConstraintDisplay).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string MarketIndexPrice_PriceCode_PriceReturn {
            get {
                return ResourceManager.GetString("MarketIndexPrice_PriceCode_PriceReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string MarketIndexPrice_PriceCode_TotalReturn {
            get {
                return ResourceManager.GetString("MarketIndexPrice_PriceCode_TotalReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string ModelAttributeScope_Account {
            get {
                return ResourceManager.GetString("ModelAttributeScope_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Transaction.
        /// </summary>
        public static string ModelAttributeScope_BankTransactionCode {
            get {
                return ResourceManager.GetString("ModelAttributeScope_BankTransactionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broker Transaction.
        /// </summary>
        public static string ModelAttributeScope_BrokerTransactionCode {
            get {
                return ResourceManager.GetString("ModelAttributeScope_BrokerTransactionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string ModelAttributeScope_Country {
            get {
                return ResourceManager.GetString("ModelAttributeScope_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custodian.
        /// </summary>
        public static string ModelAttributeScope_Custodian {
            get {
                return ResourceManager.GetString("ModelAttributeScope_Custodian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Exchange.
        /// </summary>
        public static string ModelAttributeScope_Exchange {
            get {
                return ResourceManager.GetString("ModelAttributeScope_Exchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string ModelAttributeScope_Security {
            get {
                return ResourceManager.GetString("ModelAttributeScope_Security", resourceCulture);
            }
        }
    }
}
