//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ozym.DataTransfer.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BrokerTransactionDto_SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BrokerTransactionDto_SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ozym.DataTransfer.Common.BrokerTransactionDto_SR", typeof(BrokerTransactionDto_SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date the position was originally acquired..
        /// </summary>
        public static string AcquisitionDate_Description {
            get {
                return ResourceManager.GetString("AcquisitionDate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acq. Date.
        /// </summary>
        public static string AcquisitionDate_Name {
            get {
                return ResourceManager.GetString("AcquisitionDate_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of the transaction net of fees and withholding..
        /// </summary>
        public static string Amount_Description {
            get {
                return ResourceManager.GetString("Amount_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Amount.
        /// </summary>
        public static string Amount_Name {
            get {
                return ResourceManager.GetString("Amount_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit/source of funds for the transaction..
        /// </summary>
        public static string DepSecurityId_Description {
            get {
                return ResourceManager.GetString("DepSecurityId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit / Source.
        /// </summary>
        public static string DepSecurityId_Name {
            get {
                return ResourceManager.GetString("DepSecurityId_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction fee deducted from the trade amount..
        /// </summary>
        public static string Fee_Description {
            get {
                return ResourceManager.GetString("Fee_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee.
        /// </summary>
        public static string Fee_Name {
            get {
                return ResourceManager.GetString("Fee_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to broker transactions.
        /// </summary>
        public static string Noun_Plural {
            get {
                return ResourceManager.GetString("Noun_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string Noun_Plural_Article {
            get {
                return ResourceManager.GetString("Noun_Plural_Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to broker transaction.
        /// </summary>
        public static string Noun_Singular {
            get {
                return ResourceManager.GetString("Noun_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string Noun_Singular_Article {
            get {
                return ResourceManager.GetString("Noun_Singular_Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity / shares transacted..
        /// </summary>
        public static string Quantity_Description {
            get {
                return ResourceManager.GetString("Quantity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity_Name {
            get {
                return ResourceManager.GetString("Quantity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security transacted or source of income..
        /// </summary>
        public static string SecurityId_Description {
            get {
                return ResourceManager.GetString("SecurityId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string SecurityId_Name {
            get {
                return ResourceManager.GetString("SecurityId_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settlement date of the transaction..
        /// </summary>
        public static string SettleDate_Description {
            get {
                return ResourceManager.GetString("SettleDate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settle Date.
        /// </summary>
        public static string SettleDate_Name {
            get {
                return ResourceManager.GetString("SettleDate_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot the transaction closes against..
        /// </summary>
        public static string TaxLotId_Description {
            get {
                return ResourceManager.GetString("TaxLotId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Lot.
        /// </summary>
        public static string TaxLotId_Name {
            get {
                return ResourceManager.GetString("TaxLotId_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade date of the transaction..
        /// </summary>
        public static string TradeDate_Description {
            get {
                return ResourceManager.GetString("TradeDate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Date.
        /// </summary>
        public static string TradeDate_Name {
            get {
                return ResourceManager.GetString("TradeDate_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transaction type..
        /// </summary>
        public static string TransactionCodeId_Description {
            get {
                return ResourceManager.GetString("TransactionCodeId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tran. Code.
        /// </summary>
        public static string TransactionCodeId_Name {
            get {
                return ResourceManager.GetString("TransactionCodeId_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TransactionId_Description {
            get {
                return ResourceManager.GetString("TransactionId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TransactionId_Name {
            get {
                return ResourceManager.GetString("TransactionId_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxes withheld from the trade amount..
        /// </summary>
        public static string Withholding_Description {
            get {
                return ResourceManager.GetString("Withholding_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withholding.
        /// </summary>
        public static string Withholding_Name {
            get {
                return ResourceManager.GetString("Withholding_Name", resourceCulture);
            }
        }
    }
}
