//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ozym.DataTransfer.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MarketIndexPriceDto_SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MarketIndexPriceDto_SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ozym.DataTransfer.Common.MarketIndexPriceDto_SR", typeof(MarketIndexPriceDto_SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string IndexPriceId_Description {
            get {
                return ResourceManager.GetString("IndexPriceId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string IndexPriceId_Name {
            get {
                return ResourceManager.GetString("IndexPriceId_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index valued by the record..
        /// </summary>
        public static string MarketIndexId_Description {
            get {
                return ResourceManager.GetString("MarketIndexId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string MarketIndexId_Name {
            get {
                return ResourceManager.GetString("MarketIndexId_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to index rates.
        /// </summary>
        public static string Noun_Plural {
            get {
                return ResourceManager.GetString("Noun_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string Noun_Plural_Article {
            get {
                return ResourceManager.GetString("Noun_Plural_Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to index rate.
        /// </summary>
        public static string Noun_Singular {
            get {
                return ResourceManager.GetString("Noun_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string Noun_Singular_Article {
            get {
                return ResourceManager.GetString("Noun_Singular_Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The indexed value..
        /// </summary>
        public static string Price_Description {
            get {
                return ResourceManager.GetString("Price_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Price_Name {
            get {
                return ResourceManager.GetString("Price_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of return measured by the record (e.g., price or total)..
        /// </summary>
        public static string PriceCode_Description {
            get {
                return ResourceManager.GetString("PriceCode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Type.
        /// </summary>
        public static string PriceCode_Name {
            get {
                return ResourceManager.GetString("PriceCode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of the index price record..
        /// </summary>
        public static string PriceDate_Description {
            get {
                return ResourceManager.GetString("PriceDate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string PriceDate_Name {
            get {
                return ResourceManager.GetString("PriceDate_Name", resourceCulture);
            }
        }
    }
}
