//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ozym.DataTransfer.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MarketIndexDto_SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MarketIndexDto_SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ozym.DataTransfer.Common.MarketIndexDto_SR", typeof(MarketIndexDto_SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short identifier for the index..
        /// </summary>
        public static string IndexCode_Description {
            get {
                return ResourceManager.GetString("IndexCode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        public static string IndexCode_Name {
            get {
                return ResourceManager.GetString("IndexCode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long name or description of the index..
        /// </summary>
        public static string IndexDescription_Description {
            get {
                return ResourceManager.GetString("IndexDescription_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string IndexDescription_Name {
            get {
                return ResourceManager.GetString("IndexDescription_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string IndexId_Description {
            get {
                return ResourceManager.GetString("IndexId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string IndexId_Name {
            get {
                return ResourceManager.GetString("IndexId_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to indices.
        /// </summary>
        public static string Noun_Plural {
            get {
                return ResourceManager.GetString("Noun_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string Noun_Plural_Article {
            get {
                return ResourceManager.GetString("Noun_Plural_Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to index.
        /// </summary>
        public static string Noun_Singular {
            get {
                return ResourceManager.GetString("Noun_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string Noun_Singular_Article {
            get {
                return ResourceManager.GetString("Noun_Singular_Article", resourceCulture);
            }
        }
    }
}
