//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ozym.DataTransfer.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SecurityDto_SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SecurityDto_SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ozym.DataTransfer.Common.SecurityDto_SR", typeof(SecurityDto_SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current primary identifier of the security..
        /// </summary>
        public static string CurrentSymbol_Description {
            get {
                return ResourceManager.GetString("CurrentSymbol_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        public static string CurrentySymbol_Name {
            get {
                return ResourceManager.GetString("CurrentySymbol_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags whether the security trades on a perpetual marketplace..
        /// </summary>
        public static string HasPerpetualMarket_Description {
            get {
                return ResourceManager.GetString("HasPerpetualMarket_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perpetual Market.
        /// </summary>
        public static string HasPerpetualMarket_Name {
            get {
                return ResourceManager.GetString("HasPerpetualMarket_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags whether the seurity has a perpetual value..
        /// </summary>
        public static string HasPerpetualPrice_Description {
            get {
                return ResourceManager.GetString("HasPerpetualPrice_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perpetual Price.
        /// </summary>
        public static string HasPerpetualPrice_Name {
            get {
                return ResourceManager.GetString("HasPerpetualPrice_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the company or entity underlying the security..
        /// </summary>
        public static string Issuer_Description {
            get {
                return ResourceManager.GetString("Issuer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer.
        /// </summary>
        public static string Issuer_Name {
            get {
                return ResourceManager.GetString("Issuer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to securities.
        /// </summary>
        public static string Noun_Plural {
            get {
                return ResourceManager.GetString("Noun_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string Noun_Plural_Article {
            get {
                return ResourceManager.GetString("Noun_Plural_Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to security.
        /// </summary>
        public static string Noun_Singular {
            get {
                return ResourceManager.GetString("Noun_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string Noun_Singular_Article {
            get {
                return ResourceManager.GetString("Noun_Singular_Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name / short description of the security..
        /// </summary>
        public static string SecurityDescription_Description {
            get {
                return ResourceManager.GetString("SecurityDescription_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string SecurityDescription_Name {
            get {
                return ResourceManager.GetString("SecurityDescription_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary exchange on which the security trades..
        /// </summary>
        public static string SecurityExchangeId_Description {
            get {
                return ResourceManager.GetString("SecurityExchangeId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange.
        /// </summary>
        public static string SecurityExchangeId_Name {
            get {
                return ResourceManager.GetString("SecurityExchangeId_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SecurityId_Description {
            get {
                return ResourceManager.GetString("SecurityId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SecurityId_Name {
            get {
                return ResourceManager.GetString("SecurityId_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of the security..
        /// </summary>
        public static string SecurityTypeId_Description {
            get {
                return ResourceManager.GetString("SecurityTypeId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string SecurityTypeId_Name {
            get {
                return ResourceManager.GetString("SecurityTypeId_Name", resourceCulture);
            }
        }
    }
}
