//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NjordinSight.DataTransfer.MethodParams {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ParamsMetadata {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ParamsMetadata() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NjordinSight.DataTransfer.MethodParams.ParamsMetadata", typeof(ParamsMetadata).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant growth rate applied to balance.
        /// </summary>
        internal static string FutureValueInput_GrowthRate_Description {
            get {
                return ResourceManager.GetString("FutureValueInput_GrowthRate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growth rate.
        /// </summary>
        internal static string FutureValueInput_GrowthRate_Name {
            get {
                return ResourceManager.GetString("FutureValueInput_GrowthRate_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of periods measured.
        /// </summary>
        internal static string FutureValueInput_Periods_Description {
            get {
                return ResourceManager.GetString("FutureValueInput_Periods_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periods.
        /// </summary>
        internal static string FutureValueInput_Periods_Name {
            get {
                return ResourceManager.GetString("FutureValueInput_Periods_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of each period.
        /// </summary>
        internal static string FutureValueInput_PeriodType_Description {
            get {
                return ResourceManager.GetString("FutureValueInput_PeriodType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period Type.
        /// </summary>
        internal static string FutureValueInput_PeriodType_Name {
            get {
                return ResourceManager.GetString("FutureValueInput_PeriodType_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial balance for the forecast.
        /// </summary>
        internal static string FutureValueInput_PresentValue_Description {
            get {
                return ResourceManager.GetString("FutureValueInput_PresentValue_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial balance.
        /// </summary>
        internal static string FutureValueInput_PresentValue_Name {
            get {
                return ResourceManager.GetString("FutureValueInput_PresentValue_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular amount contributed to balance.
        /// </summary>
        internal static string FutureValueInput_RegularDeposit_Description {
            get {
                return ResourceManager.GetString("FutureValueInput_RegularDeposit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular deposit.
        /// </summary>
        internal static string FutureValueInput_RegularDeposit_Name {
            get {
                return ResourceManager.GetString("FutureValueInput_RegularDeposit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date of the forecast.
        /// </summary>
        internal static string FutureValueInput_StartDate_Description {
            get {
                return ResourceManager.GetString("FutureValueInput_StartDate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        internal static string FutureValueInput_StartDate_Name {
            get {
                return ResourceManager.GetString("FutureValueInput_StartDate_Name", resourceCulture);
            }
        }
    }
}
