services:
  ozymdb:
    environment:
      - MSSQL_SA_PASSWORD=gl45WvA1Jb62uqNQ
      - OZYM_APP_PASSWORD=Ogj5ii8Scf6D6sCI
  ozymapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/8B7463519B14BF0A0E7B2C5DB703A30574C9AB1F.pfx
      - OZYM_APP_PASSWORD=Ogj5ii8Scf6D6sCI
      - DOCKER_DATABASE_SERVICE=ozymdb
    ports:
      - "5001:80"
      - "7001:443"
    volumes:
      - ${HOME}/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - ${HOME}/.dotnet/corefx/cryptography/x509stores/my:/https:ro
  ozymweb:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/8B7463519B14BF0A0E7B2C5DB703A30574C9AB1F.pfx
      - OZYM_APP_PASSWORD=Ogj5ii8Scf6D6sCI
      - DOCKER_DATABASE_SERVICE=ozymdb
      - DOCKER_API_SERVICE=ozymapi 
      - SUPERUSER_NAME=SU
      - SUPERUSER_PASSWORD=ChangeThisPassword^1234
    ports:
      - "80"
      - "443"
    volumes:
      - ${HOME}/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - ${HOME}/.dotnet/corefx/cryptography/x509stores/my:/https:ro

  ozymdb-dev:
    environment:
      - MSSQL_SA_PASSWORD=gl45WvA1Jb62uqNQ
      - OZYM_APP_PASSWORD=Ogj5ii8Scf6D6sCI
  ozymapi-dev:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - OZYM_APP_PASSWORD=Ogj5ii8Scf6D6sCI
      - DOCKER_DATABASE_SERVICE=ozymdb-dev
    ports:
      - "5001:80"
      - "7001:443"
    volumes:
      - ${HOME}/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - ${HOME}/.dotnet/corefx/cryptography/x509stores/my:/https:ro
  ozymweb-dev:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - OZYM_APP_PASSWORD=Ogj5ii8Scf6D6sCI
      - DOCKER_DATABASE_SERVICE=ozymdb-dev
      - DOCKER_API_SERVICE=ozymapi-dev 
    ports:
      - "80"
      - "443"
    volumes:
      - ${HOME}/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - ${HOME}/.dotnet/corefx/cryptography/x509stores/my:/https:ro
    