//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NjordinSight.EntityModel.Metadata {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelNoun {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelNoun() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NjordinSight.EntityModel.Metadata.ModelNoun", typeof(ModelNoun).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accounts.
        /// </summary>
        public static string Account_Plural {
            get {
                return ResourceManager.GetString("Account_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string Account_PluralArticle {
            get {
                return ResourceManager.GetString("Account_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account.
        /// </summary>
        public static string Account_Singular {
            get {
                return ResourceManager.GetString("Account_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string Account_SingularArticle {
            get {
                return ResourceManager.GetString("Account_SingularArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attributes.
        /// </summary>
        public static string AccountAttributeMemberEntry_Plural {
            get {
                return ResourceManager.GetString("AccountAttributeMemberEntry_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string AccountAttributeMemberEntry_PluralArticle {
            get {
                return ResourceManager.GetString("AccountAttributeMemberEntry_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attribute.
        /// </summary>
        public static string AccountAttributeMemberEntry_Singular {
            get {
                return ResourceManager.GetString("AccountAttributeMemberEntry_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string AccountAttributeMemberEntry_SingularArticle {
            get {
                return ResourceManager.GetString("AccountAttributeMemberEntry_SingularArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account composites.
        /// </summary>
        public static string AccountComposite_Plural {
            get {
                return ResourceManager.GetString("AccountComposite_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string AccountComposite_PluralArticle {
            get {
                return ResourceManager.GetString("AccountComposite_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account composite.
        /// </summary>
        public static string AccountComposite_Singular {
            get {
                return ResourceManager.GetString("AccountComposite_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string AccountComposite_SingularArticle {
            get {
                return ResourceManager.GetString("AccountComposite_SingularArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to composite members.
        /// </summary>
        public static string AccountCompositeMember_Plural {
            get {
                return ResourceManager.GetString("AccountCompositeMember_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string AccountCompositeMember_PluralArticle {
            get {
                return ResourceManager.GetString("AccountCompositeMember_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to composite member.
        /// </summary>
        public static string AccountCompositeMember_Singular {
            get {
                return ResourceManager.GetString("AccountCompositeMember_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string AccountCompositeMember_SingularArticle {
            get {
                return ResourceManager.GetString("AccountCompositeMember_SingularArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to custodians.
        /// </summary>
        public static string AccountCustodian_Plural {
            get {
                return ResourceManager.GetString("AccountCustodian_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string AccountCustodian_PluralArticle {
            get {
                return ResourceManager.GetString("AccountCustodian_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to custodian.
        /// </summary>
        public static string AccountCustodian_Singular {
            get {
                return ResourceManager.GetString("AccountCustodian_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string AccountCustodian_SingularArticle {
            get {
                return ResourceManager.GetString("AccountCustodian_SingularArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account objects.
        /// </summary>
        public static string AccountObject_Plural {
            get {
                return ResourceManager.GetString("AccountObject_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string AccountObject_PluralArticle {
            get {
                return ResourceManager.GetString("AccountObject_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account object.
        /// </summary>
        public static string AccountObject_Singular {
            get {
                return ResourceManager.GetString("AccountObject_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string AccountObject_SingularArticle {
            get {
                return ResourceManager.GetString("AccountObject_SingularArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wallets.
        /// </summary>
        public static string AccountWallet_Plural {
            get {
                return ResourceManager.GetString("AccountWallet_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string AccountWallet_PluralArticle {
            get {
                return ResourceManager.GetString("AccountWallet_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wallet.
        /// </summary>
        public static string AccountWallet_Singular {
            get {
                return ResourceManager.GetString("AccountWallet_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string AccountWallet_SingularArticle {
            get {
                return ResourceManager.GetString("AccountWallet_SingularArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audit events.
        /// </summary>
        public static string AuditEvent_Plural {
            get {
                return ResourceManager.GetString("AuditEvent_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string AuditEvent_PluralArticle {
            get {
                return ResourceManager.GetString("AuditEvent_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audit event.
        /// </summary>
        public static string AuditEvent_Singular {
            get {
                return ResourceManager.GetString("AuditEvent_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string AuditEvent_SingularArticle {
            get {
                return ResourceManager.GetString("AuditEvent_SingularArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bank transactions.
        /// </summary>
        public static string BankTransaction_Plural {
            get {
                return ResourceManager.GetString("BankTransaction_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string BankTransaction_PluralArticle {
            get {
                return ResourceManager.GetString("BankTransaction_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bank transaction.
        /// </summary>
        public static string BankTransaction_Singular {
            get {
                return ResourceManager.GetString("BankTransaction_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string BankTransaction_SingularArticle {
            get {
                return ResourceManager.GetString("BankTransaction_SingularArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transaction codes.
        /// </summary>
        public static string BankTransactionCode_Plural {
            get {
                return ResourceManager.GetString("BankTransactionCode_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string BankTransactionCode_PluralArticle {
            get {
                return ResourceManager.GetString("BankTransactionCode_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transaction code.
        /// </summary>
        public static string BankTransactionCode_Singular {
            get {
                return ResourceManager.GetString("BankTransactionCode_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string BankTransactionCode_SingularArticle {
            get {
                return ResourceManager.GetString("BankTransactionCode_SingularArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attributes.
        /// </summary>
        public static string BankTransactionCodeAttributeMemberEntry_Plural {
            get {
                return ResourceManager.GetString("BankTransactionCodeAttributeMemberEntry_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string BankTransactionCodeAttributeMemberEntry_PluralArticle {
            get {
                return ResourceManager.GetString("BankTransactionCodeAttributeMemberEntry_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attribute.
        /// </summary>
        public static string BankTransactionCodeAttributeMemberEntry_Singular {
            get {
                return ResourceManager.GetString("BankTransactionCodeAttributeMemberEntry_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string BankTransactionCodeAttributeMemberEntry_SingularArticle {
            get {
                return ResourceManager.GetString("BankTransactionCodeAttributeMemberEntry_SingularArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tax lots.
        /// </summary>
        public static string BrokerTaxLot_Plural {
            get {
                return ResourceManager.GetString("BrokerTaxLot_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string BrokerTaxLot_PluralArticle {
            get {
                return ResourceManager.GetString("BrokerTaxLot_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tax lot.
        /// </summary>
        public static string BrokerTaxLot_Singular {
            get {
                return ResourceManager.GetString("BrokerTaxLot_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string BrokerTaxLot_SingularArticle {
            get {
                return ResourceManager.GetString("BrokerTaxLot_SingularArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to broker transactions.
        /// </summary>
        public static string BrokerTransaction_Plural {
            get {
                return ResourceManager.GetString("BrokerTransaction_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string BrokerTransaction_PluralArticle {
            get {
                return ResourceManager.GetString("BrokerTransaction_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to broker transaction.
        /// </summary>
        public static string BrokerTransaction_Singular {
            get {
                return ResourceManager.GetString("BrokerTransaction_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string BrokerTransaction_SingularArticle {
            get {
                return ResourceManager.GetString("BrokerTransaction_SingularArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transaction codes.
        /// </summary>
        public static string BrokerTransactionCode_Plural {
            get {
                return ResourceManager.GetString("BrokerTransactionCode_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string BrokerTransactionCode_PluralArticle {
            get {
                return ResourceManager.GetString("BrokerTransactionCode_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transaction code.
        /// </summary>
        public static string BrokerTransactionCode_Singular {
            get {
                return ResourceManager.GetString("BrokerTransactionCode_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string BrokerTransactionCode_SingularArticle {
            get {
                return ResourceManager.GetString("BrokerTransactionCode_SingularArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attribues.
        /// </summary>
        public static string BrokerTransactionCodeAttributeMemberEntry_Plural {
            get {
                return ResourceManager.GetString("BrokerTransactionCodeAttributeMemberEntry_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string BrokerTransactionCodeAttributeMemberEntry_PluralArticle {
            get {
                return ResourceManager.GetString("BrokerTransactionCodeAttributeMemberEntry_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to atrribute.
        /// </summary>
        public static string BrokerTransactionCodeAttributeMemberEntry_Singular {
            get {
                return ResourceManager.GetString("BrokerTransactionCodeAttributeMemberEntry_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string BrokerTransactionCodeAttributeMemberEntry_SingularArticle {
            get {
                return ResourceManager.GetString("BrokerTransactionCodeAttributeMemberEntry_SingularArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tax lots.
        /// </summary>
        public static string BrokerTransactionTaxLot_Plural {
            get {
                return ResourceManager.GetString("BrokerTransactionTaxLot_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string BrokerTransactionTaxLot_PluralArticle {
            get {
                return ResourceManager.GetString("BrokerTransactionTaxLot_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tax lot.
        /// </summary>
        public static string BrokerTransactionTaxLot_Singular {
            get {
                return ResourceManager.GetString("BrokerTransactionTaxLot_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string BrokerTransactionTaxLot_SingularArticle {
            get {
                return ResourceManager.GetString("BrokerTransactionTaxLot_SingularArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to countries.
        /// </summary>
        public static string Country_Plural {
            get {
                return ResourceManager.GetString("Country_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string Country_PluralArticle {
            get {
                return ResourceManager.GetString("Country_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to country.
        /// </summary>
        public static string Country_Singular {
            get {
                return ResourceManager.GetString("Country_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string Country_SingularArticle {
            get {
                return ResourceManager.GetString("Country_SingularArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attributes.
        /// </summary>
        public static string CountryAttributeMemberEntry_Plural {
            get {
                return ResourceManager.GetString("CountryAttributeMemberEntry_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string CountryAttributeMemberEntry_PluralArticle {
            get {
                return ResourceManager.GetString("CountryAttributeMemberEntry_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attribute.
        /// </summary>
        public static string CountryAttributeMemberEntry_Singular {
            get {
                return ResourceManager.GetString("CountryAttributeMemberEntry_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string CountryAttributeMemberEntry_SingularArticle {
            get {
                return ResourceManager.GetString("CountryAttributeMemberEntry_SingularArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attributes.
        /// </summary>
        public static string InvestmentPerformanceAttributeMemberEntry_Plural {
            get {
                return ResourceManager.GetString("InvestmentPerformanceAttributeMemberEntry_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string InvestmentPerformanceAttributeMemberEntry_PluralArticle {
            get {
                return ResourceManager.GetString("InvestmentPerformanceAttributeMemberEntry_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attrribute.
        /// </summary>
        public static string InvestmentPerformanceAttributeMemberEntry_Singular {
            get {
                return ResourceManager.GetString("InvestmentPerformanceAttributeMemberEntry_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string InvestmentPerformanceAttributeMemberEntry_SingularArticle {
            get {
                return ResourceManager.GetString("InvestmentPerformanceAttributeMemberEntry_SingularArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to performance rows.
        /// </summary>
        public static string InvestmentPerformanceEntry_Plural {
            get {
                return ResourceManager.GetString("InvestmentPerformanceEntry_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string InvestmentPerformanceEntry_PluralArticle {
            get {
                return ResourceManager.GetString("InvestmentPerformanceEntry_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to performance row.
        /// </summary>
        public static string InvestmentPerformanceEntry_Singular {
            get {
                return ResourceManager.GetString("InvestmentPerformanceEntry_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string InvestmentPerformanceEntry_SingularArticle {
            get {
                return ResourceManager.GetString("InvestmentPerformanceEntry_SingularArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to investment models.
        /// </summary>
        public static string InvestmentStrategy_Plural {
            get {
                return ResourceManager.GetString("InvestmentStrategy_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string InvestmentStrategy_PluralArticle {
            get {
                return ResourceManager.GetString("InvestmentStrategy_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to investment model.
        /// </summary>
        public static string InvestmentStrategy_Singular {
            get {
                return ResourceManager.GetString("InvestmentStrategy_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string InvestmentStrategy_SingularArticle {
            get {
                return ResourceManager.GetString("InvestmentStrategy_SingularArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to investment targets.
        /// </summary>
        public static string InvestmentStrategyTarget_Plural {
            get {
                return ResourceManager.GetString("InvestmentStrategyTarget_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string InvestmentStrategyTarget_PluralArticle {
            get {
                return ResourceManager.GetString("InvestmentStrategyTarget_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to investment target.
        /// </summary>
        public static string InvestmentStrategyTarget_Singular {
            get {
                return ResourceManager.GetString("InvestmentStrategyTarget_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string InvestmentStrategyTarget_SingularArticle {
            get {
                return ResourceManager.GetString("InvestmentStrategyTarget_SingularArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to holidays.
        /// </summary>
        public static string MarketHoliday_Plural {
            get {
                return ResourceManager.GetString("MarketHoliday_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string MarketHoliday_PluralArticle {
            get {
                return ResourceManager.GetString("MarketHoliday_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to holiday.
        /// </summary>
        public static string MarketHoliday_Singular {
            get {
                return ResourceManager.GetString("MarketHoliday_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string MarketHoliday_SingularArticle {
            get {
                return ResourceManager.GetString("MarketHoliday_SingularArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to observances.
        /// </summary>
        public static string MarketHolidaySchedule_Plural {
            get {
                return ResourceManager.GetString("MarketHolidaySchedule_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string MarketHolidaySchedule_PluralArticle {
            get {
                return ResourceManager.GetString("MarketHolidaySchedule_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to observance.
        /// </summary>
        public static string MarketHolidaySchedule_Singular {
            get {
                return ResourceManager.GetString("MarketHolidaySchedule_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string MarketHolidaySchedule_SingularArticle {
            get {
                return ResourceManager.GetString("MarketHolidaySchedule_SingularArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to market indexes.
        /// </summary>
        public static string MarketIndex_Plural {
            get {
                return ResourceManager.GetString("MarketIndex_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string MarketIndex_PluralArticle {
            get {
                return ResourceManager.GetString("MarketIndex_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to market index.
        /// </summary>
        public static string MarketIndex_Singular {
            get {
                return ResourceManager.GetString("MarketIndex_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string MarketIndex_SingularArticle {
            get {
                return ResourceManager.GetString("MarketIndex_SingularArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to index rates.
        /// </summary>
        public static string MarketIndexPrice_Plural {
            get {
                return ResourceManager.GetString("MarketIndexPrice_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string MarketIndexPrice_PluralArticle {
            get {
                return ResourceManager.GetString("MarketIndexPrice_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to index rate.
        /// </summary>
        public static string MarketIndexPrice_Singular {
            get {
                return ResourceManager.GetString("MarketIndexPrice_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string MarketIndexPrice_SingularArticle {
            get {
                return ResourceManager.GetString("MarketIndexPrice_SingularArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attributes.
        /// </summary>
        public static string ModelAttribute_Plural {
            get {
                return ResourceManager.GetString("ModelAttribute_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string ModelAttribute_PluralArticle {
            get {
                return ResourceManager.GetString("ModelAttribute_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attribute.
        /// </summary>
        public static string ModelAttribute_Singular {
            get {
                return ResourceManager.GetString("ModelAttribute_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string ModelAttribute_SingularArticle {
            get {
                return ResourceManager.GetString("ModelAttribute_SingularArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attribute values.
        /// </summary>
        public static string ModelAttributeMember_Plural {
            get {
                return ResourceManager.GetString("ModelAttributeMember_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string ModelAttributeMember_PluralArticle {
            get {
                return ResourceManager.GetString("ModelAttributeMember_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attribute value.
        /// </summary>
        public static string ModelAttributeMember_Singular {
            get {
                return ResourceManager.GetString("ModelAttributeMember_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string ModelAttributeMember_SingularArticle {
            get {
                return ResourceManager.GetString("ModelAttributeMember_SingularArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attribute scopes.
        /// </summary>
        public static string ModelAttributeScope_Plural {
            get {
                return ResourceManager.GetString("ModelAttributeScope_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string ModelAttributeScope_PluralArticle {
            get {
                return ResourceManager.GetString("ModelAttributeScope_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attribute scope.
        /// </summary>
        public static string ModelAttributeScope_Singular {
            get {
                return ResourceManager.GetString("ModelAttributeScope_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string ModelAttributeScope_SingularArticle {
            get {
                return ResourceManager.GetString("ModelAttributeScope_SingularArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to report configurations.
        /// </summary>
        public static string ReportConfiguration_Plural {
            get {
                return ResourceManager.GetString("ReportConfiguration_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string ReportConfiguration_PluralArticle {
            get {
                return ResourceManager.GetString("ReportConfiguration_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to report configuration.
        /// </summary>
        public static string ReportConfiguration_Singular {
            get {
                return ResourceManager.GetString("ReportConfiguration_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string ReportConfiguration_SingularArticle {
            get {
                return ResourceManager.GetString("ReportConfiguration_SingularArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to style sheets.
        /// </summary>
        public static string ReportStyleSheet_Plural {
            get {
                return ResourceManager.GetString("ReportStyleSheet_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string ReportStyleSheet_PluralArticle {
            get {
                return ResourceManager.GetString("ReportStyleSheet_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to style sheet.
        /// </summary>
        public static string ReportStyleSheet_Singular {
            get {
                return ResourceManager.GetString("ReportStyleSheet_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string ReportStyleSheet_SingularArticle {
            get {
                return ResourceManager.GetString("ReportStyleSheet_SingularArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images.
        /// </summary>
        public static string ResourceImage_Plural {
            get {
                return ResourceManager.GetString("ResourceImage_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string ResourceImage_PluralArticle {
            get {
                return ResourceManager.GetString("ResourceImage_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image.
        /// </summary>
        public static string ResourceImage_Singular {
            get {
                return ResourceManager.GetString("ResourceImage_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string ResourceImage_SingularArticle {
            get {
                return ResourceManager.GetString("ResourceImage_SingularArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to securities.
        /// </summary>
        public static string Security_Plural {
            get {
                return ResourceManager.GetString("Security_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string Security_PluralArticle {
            get {
                return ResourceManager.GetString("Security_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to security.
        /// </summary>
        public static string Security_Singular {
            get {
                return ResourceManager.GetString("Security_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string Security_SingularArticle {
            get {
                return ResourceManager.GetString("Security_SingularArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attributes.
        /// </summary>
        public static string SecurityAttributeMemberEntry_Plural {
            get {
                return ResourceManager.GetString("SecurityAttributeMemberEntry_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string SecurityAttributeMemberEntry_PluralArticle {
            get {
                return ResourceManager.GetString("SecurityAttributeMemberEntry_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attribute.
        /// </summary>
        public static string SecurityAttributeMemberEntry_Singular {
            get {
                return ResourceManager.GetString("SecurityAttributeMemberEntry_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string SecurityAttributeMemberEntry_SingularArticle {
            get {
                return ResourceManager.GetString("SecurityAttributeMemberEntry_SingularArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exchanges.
        /// </summary>
        public static string SecurityExchange_Plural {
            get {
                return ResourceManager.GetString("SecurityExchange_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string SecurityExchange_PluralArticle {
            get {
                return ResourceManager.GetString("SecurityExchange_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exchange.
        /// </summary>
        public static string SecurityExchange_Singular {
            get {
                return ResourceManager.GetString("SecurityExchange_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string SecurityExchange_SingularArticle {
            get {
                return ResourceManager.GetString("SecurityExchange_SingularArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prices.
        /// </summary>
        public static string SecurityPrice_Plural {
            get {
                return ResourceManager.GetString("SecurityPrice_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string SecurityPrice_PluralArticle {
            get {
                return ResourceManager.GetString("SecurityPrice_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to price.
        /// </summary>
        public static string SecurityPrice_Singular {
            get {
                return ResourceManager.GetString("SecurityPrice_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string SecurityPrice_SingularArticle {
            get {
                return ResourceManager.GetString("SecurityPrice_SingularArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to symbols.
        /// </summary>
        public static string SecuritySymbol_Plural {
            get {
                return ResourceManager.GetString("SecuritySymbol_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string SecuritySymbol_PluralArticle {
            get {
                return ResourceManager.GetString("SecuritySymbol_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to security symbol.
        /// </summary>
        public static string SecuritySymbol_Singular {
            get {
                return ResourceManager.GetString("SecuritySymbol_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string SecuritySymbol_SingularArticle {
            get {
                return ResourceManager.GetString("SecuritySymbol_SingularArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to symbol maps.
        /// </summary>
        public static string SecuritySymbolMap_Plural {
            get {
                return ResourceManager.GetString("SecuritySymbolMap_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string SecuritySymbolMap_PluralArticle {
            get {
                return ResourceManager.GetString("SecuritySymbolMap_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to symbol map.
        /// </summary>
        public static string SecuritySymbolMap_Singular {
            get {
                return ResourceManager.GetString("SecuritySymbolMap_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string SecuritySymbolMap_SingularArticle {
            get {
                return ResourceManager.GetString("SecuritySymbolMap_SingularArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to symbol types.
        /// </summary>
        public static string SecuritySymbolType_Plural {
            get {
                return ResourceManager.GetString("SecuritySymbolType_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string SecuritySymbolType_PluralArticle {
            get {
                return ResourceManager.GetString("SecuritySymbolType_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to symbol type.
        /// </summary>
        public static string SecuritySymbolType_Singular {
            get {
                return ResourceManager.GetString("SecuritySymbolType_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string SecuritySymbolType_SingularArticle {
            get {
                return ResourceManager.GetString("SecuritySymbolType_SingularArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to security types.
        /// </summary>
        public static string SecurityType_Plural {
            get {
                return ResourceManager.GetString("SecurityType_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string SecurityType_PluralArticle {
            get {
                return ResourceManager.GetString("SecurityType_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to security type.
        /// </summary>
        public static string SecurityType_Singular {
            get {
                return ResourceManager.GetString("SecurityType_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string SecurityType_SingularArticle {
            get {
                return ResourceManager.GetString("SecurityType_SingularArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to security type groups.
        /// </summary>
        public static string SecurityTypeGroup_Plural {
            get {
                return ResourceManager.GetString("SecurityTypeGroup_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string SecurityTypeGroup_PluralArticle {
            get {
                return ResourceManager.GetString("SecurityTypeGroup_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to security type group.
        /// </summary>
        public static string SecurityTypeGroup_Singular {
            get {
                return ResourceManager.GetString("SecurityTypeGroup_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string SecurityTypeGroup_SingularArticle {
            get {
                return ResourceManager.GetString("SecurityTypeGroup_SingularArticle", resourceCulture);
            }
        }
    }
}
