//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ozym.DataTransfer.MethodParams {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DisplayString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ozym.DataTransfer.MethodParams.DisplayString", typeof(DisplayString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account to filter results to.
        /// </summary>
        public static string AccountBalanceInput_AccountId_Description {
            get {
                return ResourceManager.GetString("AccountBalanceInput_AccountId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string AccountBalanceInput_AccountId_Name {
            get {
                return ResourceManager.GetString("AccountBalanceInput_AccountId_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference date for balance.
        /// </summary>
        public static string AccountBalanceInput_AsOfDate_Description {
            get {
                return ResourceManager.GetString("AccountBalanceInput_AsOfDate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As of date.
        /// </summary>
        public static string AccountBalanceInput_AsOfDate_Name {
            get {
                return ResourceManager.GetString("AccountBalanceInput_AsOfDate_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account to filter results to.
        /// </summary>
        public static string BankTransactionInput_AccountId_Description {
            get {
                return ResourceManager.GetString("BankTransactionInput_AccountId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string BankTransactionInput_AccountId_Name {
            get {
                return ResourceManager.GetString("BankTransactionInput_AccountId_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference date for the offset range.
        /// </summary>
        public static string BankTransactionInput_AsOfDate_Description {
            get {
                return ResourceManager.GetString("BankTransactionInput_AsOfDate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As of date.
        /// </summary>
        public static string BankTransactionInput_AsOfDate_Name {
            get {
                return ResourceManager.GetString("BankTransactionInput_AsOfDate_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign this attribute as the parent category.
        /// </summary>
        public static string BankTransactionInput_Attribute1_Description {
            get {
                return ResourceManager.GetString("BankTransactionInput_Attribute1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category 1.
        /// </summary>
        public static string BankTransactionInput_Attribute1_Name {
            get {
                return ResourceManager.GetString("BankTransactionInput_Attribute1_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign this attribute as the child category.
        /// </summary>
        public static string BankTransactionInput_Attribute2_Description {
            get {
                return ResourceManager.GetString("BankTransactionInput_Attribute2_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category 2.
        /// </summary>
        public static string BankTransactionInput_Attribute2_Name {
            get {
                return ResourceManager.GetString("BankTransactionInput_Attribute2_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of days prior to as of date to include.
        /// </summary>
        public static string BankTransactionInput_DayOffset_Description {
            get {
                return ResourceManager.GetString("BankTransactionInput_DayOffset_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day offset.
        /// </summary>
        public static string BankTransactionInput_DayOffset_Name {
            get {
                return ResourceManager.GetString("BankTransactionInput_DayOffset_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant growth rate applied to balance.
        /// </summary>
        public static string FutureValueInput_GrowthRate_Description {
            get {
                return ResourceManager.GetString("FutureValueInput_GrowthRate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growth Rate.
        /// </summary>
        public static string FutureValueInput_GrowthRate_Name {
            get {
                return ResourceManager.GetString("FutureValueInput_GrowthRate_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of periods measured.
        /// </summary>
        public static string FutureValueInput_Periods_Description {
            get {
                return ResourceManager.GetString("FutureValueInput_Periods_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periods.
        /// </summary>
        public static string FutureValueInput_Periods_Name {
            get {
                return ResourceManager.GetString("FutureValueInput_Periods_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of each period.
        /// </summary>
        public static string FutureValueInput_PeriodType_Description {
            get {
                return ResourceManager.GetString("FutureValueInput_PeriodType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period Type.
        /// </summary>
        public static string FutureValueInput_PeriodType_Name {
            get {
                return ResourceManager.GetString("FutureValueInput_PeriodType_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial balance for the forecast.
        /// </summary>
        public static string FutureValueInput_PresentValue_Description {
            get {
                return ResourceManager.GetString("FutureValueInput_PresentValue_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Balance.
        /// </summary>
        public static string FutureValueInput_PresentValue_Name {
            get {
                return ResourceManager.GetString("FutureValueInput_PresentValue_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular amount contributed to balance.
        /// </summary>
        public static string FutureValueInput_RegularDeposit_Description {
            get {
                return ResourceManager.GetString("FutureValueInput_RegularDeposit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Deposit.
        /// </summary>
        public static string FutureValueInput_RegularDeposit_Name {
            get {
                return ResourceManager.GetString("FutureValueInput_RegularDeposit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date of the forecast.
        /// </summary>
        public static string FutureValueInput_StartDate_Description {
            get {
                return ResourceManager.GetString("FutureValueInput_StartDate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string FutureValueInput_StartDate_Name {
            get {
                return ResourceManager.GetString("FutureValueInput_StartDate_Name", resourceCulture);
            }
        }
    }
}
