//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ozym.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ozym.Web.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ozym.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ozym is a web-application for financial management and reporting, powered by Blazor and ASP.NET..
        /// </summary>
        internal static string ApplicationSummary {
            get {
                return ResourceManager.GetString("ApplicationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Select &gt;.
        /// </summary>
        internal static string Caption_InputSelect_Placeholder {
            get {
                return ResourceManager.GetString("Caption_InputSelect_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        internal static string Caption_IsConfirmed {
            get {
                return ResourceManager.GetString("Caption_IsConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not confirmed.
        /// </summary>
        internal static string Caption_IsNotConfirmed {
            get {
                return ResourceManager.GetString("Caption_IsNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market quotes.
        /// </summary>
        internal static string ComponentTile_MarketQuotes {
            get {
                return ResourceManager.GetString("ComponentTile_MarketQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select attribute.
        /// </summary>
        internal static string ComponentTitle_AttributeSelector {
            get {
                return ResourceManager.GetString("ComponentTitle_AttributeSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future value calculator.
        /// </summary>
        internal static string ComponentTitle_FutureValueCalculator {
            get {
                return ResourceManager.GetString("ComponentTitle_FutureValueCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host terminated unexpectedly..
        /// </summary>
        internal static string Exception_Application_Fatal {
            get {
                return ResourceManager.GetString("Exception_Application_Fatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred:.
        /// </summary>
        internal static string Exception_Message_Generic {
            get {
                return ResourceManager.GetString("Exception_Message_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The relative base URI is expected to be a string beginning with &apos;/&apos;..
        /// </summary>
        internal static string Exception_Navigation_BaseUriNotValid {
            get {
                return ResourceManager.GetString("Exception_Navigation_BaseUriNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred. Please submit a ticket with the package maintainer, or try your request again.
        ///
        ///If submitting a ticket, please include the following timestamp in your report: {0}.
        /// </summary>
        internal static string Exception_Unhandled_Critical {
            get {
                return ResourceManager.GetString("Exception_Unhandled_Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string PageTitle_About {
            get {
                return ResourceManager.GetString("PageTitle_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string PageTitle_Dashboard {
            get {
                return ResourceManager.GetString("PageTitle_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string PageTitle_Home {
            get {
                return ResourceManager.GetString("PageTitle_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No title).
        /// </summary>
        internal static string PageTitle_NotFound {
            get {
                return ResourceManager.GetString("PageTitle_NotFound", resourceCulture);
            }
        }
    }
}
