//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EulerFinancial.Logging.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DebugMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DebugMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EulerFinancial.Logging.Resources.DebugMessage", typeof(DebugMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Controller} initialized..
        /// </summary>
        public static string Controller_Create_Success {
            get {
                return ResourceManager.GetString("Controller_Create_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Model} created..
        /// </summary>
        public static string Model_Create_Success {
            get {
                return ResourceManager.GetString("Model_Create_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Model} deleted..
        /// </summary>
        public static string Model_Delete_Success {
            get {
                return ResourceManager.GetString("Model_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Model} updated..
        /// </summary>
        public static string Model_Update_Success {
            get {
                return ResourceManager.GetString("Model_Update_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Model} addition to context did not yield expected entity state.
        ///Expected&lt;{ExpectedState}&gt; Observed&lt;{ObservedState}&gt;.
        /// </summary>
        public static string ModelBatch_Add_Failure {
            get {
                return ResourceManager.GetString("ModelBatch_Add_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Model} added to context pending save..
        /// </summary>
        public static string ModelBatch_Add_Success {
            get {
                return ResourceManager.GetString("ModelBatch_Add_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Model} deletion from context did not yield expected entity state.
        ///Expected&lt;{ExpectedState}&gt; Observed&lt;{ObservedState}&gt;.
        /// </summary>
        public static string ModelBatch_Delete_Failure {
            get {
                return ResourceManager.GetString("ModelBatch_Delete_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Model} deleted from context pending save..
        /// </summary>
        public static string ModelBatch_Delete_Success {
            get {
                return ResourceManager.GetString("ModelBatch_Delete_Success", resourceCulture);
            }
        }
    }
}
