//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EulerFinancial.Logging.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InformationMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InformationMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EulerFinancial.Logging.Resources.InformationMessage", typeof(InformationMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes successfully saved..
        /// </summary>
        internal static string Context_Save_Success {
            get {
                return ResourceManager.GetString("Context_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Model} created..
        /// </summary>
        internal static string Model_Create_Success {
            get {
                return ResourceManager.GetString("Model_Create_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Model} deleted..
        /// </summary>
        internal static string Model_Delete_Success {
            get {
                return ResourceManager.GetString("Model_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Model} accessed..
        /// </summary>
        internal static string Model_Read_Success {
            get {
                return ResourceManager.GetString("Model_Read_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {@Model} updated..
        /// </summary>
        internal static string Model_Update_Success {
            get {
                return ResourceManager.GetString("Model_Update_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {ModelType} changes saved. {Count} records added/updated/deleted..
        /// </summary>
        internal static string ModelBatch_Save_Success {
            get {
                return ResourceManager.GetString("ModelBatch_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {ModelType} search returned {Count} records..
        /// </summary>
        internal static string ModelSearch_Request_ReturnSuccess {
            get {
                return ResourceManager.GetString("ModelSearch_Request_ReturnSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search requested for {ModelType} matching {Expression} with with limit {MaxCount}..
        /// </summary>
        internal static string ModelSearch_Request_SubmitSuccess {
            get {
                return ResourceManager.GetString("ModelSearch_Request_SubmitSuccess", resourceCulture);
            }
        }
    }
}
