//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NjordinSight.DataTransfer.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountDto_SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountDto_SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NjordinSight.DataTransfer.Common.AccountDto_SR", typeof(AccountDto_SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institution that holds the account..
        /// </summary>
        public static string AccountCustodianId_Description {
            get {
                return ResourceManager.GetString("AccountCustodianId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custodian.
        /// </summary>
        public static string AccountCustodianId_Name {
            get {
                return ResourceManager.GetString("AccountCustodianId_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custodian identifier for the account..
        /// </summary>
        public static string AccountNumber_Description {
            get {
                return ResourceManager.GetString("AccountNumber_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        public static string AccountNumber_Name {
            get {
                return ResourceManager.GetString("AccountNumber_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date on and before which transaction edits are restricted..
        /// </summary>
        public static string BooksClosedDate_Description {
            get {
                return ResourceManager.GetString("BooksClosedDate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books Closed.
        /// </summary>
        public static string BooksClosedDate_Name {
            get {
                return ResourceManager.GetString("BooksClosedDate_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date account closed..
        /// </summary>
        public static string CloseDate_Description {
            get {
                return ResourceManager.GetString("CloseDate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Date.
        /// </summary>
        public static string CloseDate_Name {
            get {
                return ResourceManager.GetString("CloseDate_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description / purpose of the account..
        /// </summary>
        public static string Description_Description {
            get {
                return ResourceManager.GetString("Description_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description_Name {
            get {
                return ResourceManager.GetString("Description_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name of the account..
        /// </summary>
        public static string DisplayName_Description {
            get {
                return ResourceManager.GetString("DisplayName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DisplayName_Name {
            get {
                return ResourceManager.GetString("DisplayName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag indicating whether  the account has bank transactions..
        /// </summary>
        public static string HasBankTransaction_Description {
            get {
                return ResourceManager.GetString("HasBankTransaction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Bank.
        /// </summary>
        public static string HasBankTransaction_Name {
            get {
                return ResourceManager.GetString("HasBankTransaction_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag indicating whether  the account has broker transactions..
        /// </summary>
        public static string HasBrokerTransaction_Description {
            get {
                return ResourceManager.GetString("HasBrokerTransaction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Brokerage.
        /// </summary>
        public static string HasBrokerTransaction_Name {
            get {
                return ResourceManager.GetString("HasBrokerTransaction_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag indiciating whether the account has associated digital wallets..
        /// </summary>
        public static string HasWallet_Description {
            get {
                return ResourceManager.GetString("HasWallet_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Wallets.
        /// </summary>
        public static string HasWallet_Name {
            get {
                return ResourceManager.GetString("HasWallet_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Id_Description {
            get {
                return ResourceManager.GetString("Id_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Id_Name {
            get {
                return ResourceManager.GetString("Id_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short text identifier of the account..
        /// </summary>
        public static string ShortCode_Description {
            get {
                return ResourceManager.GetString("ShortCode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Code.
        /// </summary>
        public static string ShortCode_Name {
            get {
                return ResourceManager.GetString("ShortCode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date the account started..
        /// </summary>
        public static string StartDate_Description {
            get {
                return ResourceManager.GetString("StartDate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate_Name {
            get {
                return ResourceManager.GetString("StartDate_Name", resourceCulture);
            }
        }
    }
}
