//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NjordinSight.DataTransfer.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SecurityTypeGroupDto_SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SecurityTypeGroupDto_SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NjordinSight.DataTransfer.Common.SecurityTypeGroupDto_SR", typeof(SecurityTypeGroupDto_SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates whether securities in this type group can be external deposit sources to brokerage accounts..
        /// </summary>
        public static string DepositSource_Description {
            get {
                return ResourceManager.GetString("DepositSource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Deposit Source.
        /// </summary>
        public static string DepositSource_Name {
            get {
                return ResourceManager.GetString("DepositSource_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order in which the type group is displayed in reports..
        /// </summary>
        public static string DisplayOrder_Description {
            get {
                return ResourceManager.GetString("DisplayOrder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Order.
        /// </summary>
        public static string DisplayOrder_Name {
            get {
                return ResourceManager.GetString("DisplayOrder_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type groups.
        /// </summary>
        public static string Noun_Plural {
            get {
                return ResourceManager.GetString("Noun_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string Noun_Plural_Article {
            get {
                return ResourceManager.GetString("Noun_Plural_Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type group.
        /// </summary>
        public static string Noun_Singular {
            get {
                return ResourceManager.GetString("Noun_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string Noun_Singular_Article {
            get {
                return ResourceManager.GetString("Noun_Singular_Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SecurityTypeGroupId_Description {
            get {
                return ResourceManager.GetString("SecurityTypeGroupId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SecurityTypeGroupId_Name {
            get {
                return ResourceManager.GetString("SecurityTypeGroupId_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name of the group..
        /// </summary>
        public static string SecurityTypeGroupName_Description {
            get {
                return ResourceManager.GetString("SecurityTypeGroupName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        public static string SecurityTypeGroupName_Name {
            get {
                return ResourceManager.GetString("SecurityTypeGroupName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates whether securities in this type group can be the source of broker transactions..
        /// </summary>
        public static string Transactable_Description {
            get {
                return ResourceManager.GetString("Transactable_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactable.
        /// </summary>
        public static string Transactable_Name {
            get {
                return ResourceManager.GetString("Transactable_Name", resourceCulture);
            }
        }
    }
}
