//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NjordinSight.DataTransfer.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SecuritySymbolMapDto_SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SecuritySymbolMapDto_SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NjordinSight.DataTransfer.Common.SecuritySymbolMapDto_SR", typeof(SecuritySymbolMapDto_SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custodian to which the mapping applies..
        /// </summary>
        public static string AccountCustodianId_Description {
            get {
                return ResourceManager.GetString("AccountCustodianId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custodian.
        /// </summary>
        public static string AccountCustodianId_Name {
            get {
                return ResourceManager.GetString("AccountCustodianId_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier used by the custodian..
        /// </summary>
        public static string CustodianSymbol_Description {
            get {
                return ResourceManager.GetString("CustodianSymbol_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol (Custodian).
        /// </summary>
        public static string CustodianSymbol_Name {
            get {
                return ResourceManager.GetString("CustodianSymbol_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to symbol maps.
        /// </summary>
        public static string Noun_Plural {
            get {
                return ResourceManager.GetString("Noun_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string Noun_Plural_Article {
            get {
                return ResourceManager.GetString("Noun_Plural_Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to symbol map.
        /// </summary>
        public static string Noun_Singular {
            get {
                return ResourceManager.GetString("Noun_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string Noun_Singular_Article {
            get {
                return ResourceManager.GetString("Noun_Singular_Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SecuritySymbolId_Description {
            get {
                return ResourceManager.GetString("SecuritySymbolId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SecuritySymbolId_Name {
            get {
                return ResourceManager.GetString("SecuritySymbolId_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier used by the app..
        /// </summary>
        public static string SymbolMapId_Description {
            get {
                return ResourceManager.GetString("SymbolMapId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol (Application).
        /// </summary>
        public static string SymbolMapId_Name {
            get {
                return ResourceManager.GetString("SymbolMapId_Name", resourceCulture);
            }
        }
    }
}
