//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NjordinSight.Logging.Templates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NjordinSight.Logging.Templates.ExceptionMessage", typeof(ExceptionMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding {@Model} returned an unexpected state.
        ///Expected&lt;{ExpectedState}&gt; Observed&lt;{ObservedState}&gt;.
        /// </summary>
        internal static string ModelService_AfterAdd_InvalidState {
            get {
                return ResourceManager.GetString("ModelService_AfterAdd_InvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting {@Model} returned an unexpected state.
        ///Expected&lt;{ExpectedState}&gt; Observed&lt;{ObservedState}&gt;.
        /// </summary>
        internal static string ModelService_AfterDelete_InvalidState {
            get {
                return ResourceManager.GetString("ModelService_AfterDelete_InvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {@Service} initialized failed..
        /// </summary>
        internal static string ModelService_InitializationFailed {
            get {
                return ResourceManager.GetString("ModelService_InitializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {@Service} has not been initialized..
        /// </summary>
        internal static string ModelService_NotInitialized {
            get {
                return ResourceManager.GetString("ModelService_NotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parent key for {Service} has not been set..
        /// </summary>
        internal static string ModelService_ParentKeyNotSet {
            get {
                return ResourceManager.GetString("ModelService_ParentKeyNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {@Model} could not be accessed..
        /// </summary>
        internal static string ModelService_ReadSingle_Failed {
            get {
                return ResourceManager.GetString("ModelService_ReadSingle_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured when saving changes. Another user may have modified the same entries. Refresh results and re-apply changes..
        /// </summary>
        internal static string ModelService_SaveChanges_ConcurrencyConflict {
            get {
                return ResourceManager.GetString("ModelService_SaveChanges_ConcurrencyConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes were not saved..
        /// </summary>
        internal static string ModelService_SaveChanges_Failed {
            get {
                return ResourceManager.GetString("ModelService_SaveChanges_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception occurred. Please submit a ticket with the package maintainer, or try your request again.
        ///
        ///If submitting a ticket, please include the following timestamp in your report:
        ///{0}.
        /// </summary>
        internal static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
    }
}
