//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EulerFinancial.UserInterface {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EulerFinancial.UserInterface.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Button_Create_Caption {
            get {
                return ResourceManager.GetString("Button_Create_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Button_Delete_Caption {
            get {
                return ResourceManager.GetString("Button_Delete_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Button_Edit_Caption {
            get {
                return ResourceManager.GetString("Button_Edit_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Button_Index_Caption {
            get {
                return ResourceManager.GetString("Button_Index_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Button_Save_Caption {
            get {
                return ResourceManager.GetString("Button_Save_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Button_Search_Caption {
            get {
                return ResourceManager.GetString("Button_Search_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0}.
        /// </summary>
        public static string DataGrid_NewLine_Caption {
            get {
                return ResourceManager.GetString("DataGrid_NewLine_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} could not be saved. The errors below must be resolved:.
        /// </summary>
        public static string EditForm_ValidationFailed {
            get {
                return ResourceManager.GetString("EditForm_ValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} could not be saved. The errors below must be resolved:.
        /// </summary>
        public static string EditFormList_ValidationFailed {
            get {
                return ResourceManager.GetString("EditFormList_ValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for:.
        /// </summary>
        public static string InputSelect_SearchField_Caption {
            get {
                return ResourceManager.GetString("InputSelect_SearchField_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Page_Loading_Caption {
            get {
                return ResourceManager.GetString("Page_Loading_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new account.
        /// </summary>
        public static string Title_AccountCreate {
            get {
                return ResourceManager.GetString("Title_AccountCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Details.
        /// </summary>
        public static string Title_AccountDetail {
            get {
                return ResourceManager.GetString("Title_AccountDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Edit.
        /// </summary>
        public static string Title_AccountEdit {
            get {
                return ResourceManager.GetString("Title_AccountEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string Title_AccountIndex {
            get {
                return ResourceManager.GetString("Title_AccountIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Edit wallets.
        /// </summary>
        public static string Title_AccountWalletsEdit {
            get {
                return ResourceManager.GetString("Title_AccountWalletsEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Title_ApplicationHome {
            get {
                return ResourceManager.GetString("Title_ApplicationHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No title).
        /// </summary>
        public static string Title_NotFound {
            get {
                return ResourceManager.GetString("Title_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not authenticated.
        /// </summary>
        public static string User_NotAuthenticated_Caption {
            get {
                return ResourceManager.GetString("User_NotAuthenticated_Caption", resourceCulture);
            }
        }
    }
}
