//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NjordFinance.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DefaultConfiguration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefaultConfiguration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NjordFinance.Web.Resources.DefaultConfiguration", typeof(DefaultConfiguration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;MenuGuid&quot;: &quot;3e818369-9889-4b49-b565-244d3bc93217&quot;,
        ///  &quot;IconKey&quot;: null,
        ///  &quot;Caption&quot;: null,
        ///  &quot;UriStem&quot;: null,
        ///  &quot;Children&quot;: {
        ///    &quot;0&quot;: {
        ///      &quot;IconKey&quot;: null,
        ///      &quot;Caption&quot;: &quot;Accounts&quot;,
        ///      &quot;UriStem&quot;: null,
        ///      &quot;Children&quot;: {
        ///        &quot;1&quot;: {
        ///          &quot;IconKey&quot;: null,
        ///          &quot;Caption&quot;: &quot;Accounts&quot;,
        ///          &quot;UriStem&quot;: &quot;/accounts&quot;,
        ///          &quot;Children&quot;: {},
        ///          &quot;HasChildren&quot;: false
        ///        },
        ///        &quot;2&quot;: {
        ///          &quot;IconKey&quot;: null,
        ///          &quot;Caption&quot;: &quot;Composites&quot;,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NavigationMenu {
            get {
                return ResourceManager.GetString("NavigationMenu", resourceCulture);
            }
        }
    }
}
