//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NjordFinance.Web.Components {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NjordFinance.Web.Components.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Caption_Button_Cancel {
            get {
                return ResourceManager.GetString("Caption_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Caption_Button_Delete {
            get {
                return ResourceManager.GetString("Caption_Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Caption_Button_Save {
            get {
                return ResourceManager.GetString("Caption_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Caption_Button_Search {
            get {
                return ResourceManager.GetString("Caption_Button_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New {0}.
        /// </summary>
        public static string Caption_CreateNew {
            get {
                return ResourceManager.GetString("Caption_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}.
        /// </summary>
        public static string Caption_DeleteMany {
            get {
                return ResourceManager.GetString("Caption_DeleteMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}.
        /// </summary>
        public static string Caption_DeleteSingle {
            get {
                return ResourceManager.GetString("Caption_DeleteSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page/component is not available at this time. Please try again later or report this message to the project maintainer..
        /// </summary>
        public static string Caption_DevelopmentPlaceholder {
            get {
                return ResourceManager.GetString("Caption_DevelopmentPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit {0}.
        /// </summary>
        public static string Caption_EditMany {
            get {
                return ResourceManager.GetString("Caption_EditMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit {0}.
        /// </summary>
        public static string Caption_EditSingle {
            get {
                return ResourceManager.GetString("Caption_EditSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Select &gt;.
        /// </summary>
        public static string Caption_InputSelect_Prompt {
            get {
                return ResourceManager.GetString("Caption_InputSelect_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for:.
        /// </summary>
        public static string Caption_InputSelect_SearchField {
            get {
                return ResourceManager.GetString("Caption_InputSelect_SearchField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Caption_NavigateBack {
            get {
                return ResourceManager.GetString("Caption_NavigateBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to {0}.
        /// </summary>
        public static string Caption_NavigateBackTo {
            get {
                return ResourceManager.GetString("Caption_NavigateBackTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No content).
        /// </summary>
        public static string Caption_NoContent {
            get {
                return ResourceManager.GetString("Caption_NoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save {0}.
        /// </summary>
        public static string Caption_SaveMany {
            get {
                return ResourceManager.GetString("Caption_SaveMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save {0}.
        /// </summary>
        public static string Caption_SaveSingle {
            get {
                return ResourceManager.GetString("Caption_SaveSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View {0}.
        /// </summary>
        public static string Caption_ViewMany {
            get {
                return ResourceManager.GetString("Caption_ViewMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View {0}.
        /// </summary>
        public static string Caption_ViewSingle {
            get {
                return ResourceManager.GetString("Caption_ViewSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string DialogResult_Abort {
            get {
                return ResourceManager.GetString("DialogResult_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DialogResult_Cancel {
            get {
                return ResourceManager.GetString("DialogResult_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string DialogResult_Continue {
            get {
                return ResourceManager.GetString("DialogResult_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DialogResult_Delete {
            get {
                return ResourceManager.GetString("DialogResult_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        public static string DialogResult_Ignore {
            get {
                return ResourceManager.GetString("DialogResult_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string DialogResult_No {
            get {
                return ResourceManager.GetString("DialogResult_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string DialogResult_None {
            get {
                return ResourceManager.GetString("DialogResult_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string DialogResult_OK {
            get {
                return ResourceManager.GetString("DialogResult_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string DialogResult_Retry {
            get {
                return ResourceManager.GetString("DialogResult_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again.
        /// </summary>
        public static string DialogResult_TryAgain {
            get {
                return ResourceManager.GetString("DialogResult_TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string DialogResult_Yes {
            get {
                return ResourceManager.GetString("DialogResult_Yes", resourceCulture);
            }
        }
    }
}
