//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NjordinSight.BusinessLogic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DisplayString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NjordinSight.BusinessLogic.DisplayString", typeof(DisplayString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity to close in each lot..
        /// </summary>
        public static string AllocationInstructionRow_ClosingQuantity_Description {
            get {
                return ResourceManager.GetString("AllocationInstructionRow_ClosingQuantity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close shares.
        /// </summary>
        public static string AllocationInstructionRow_ClosingQuantity_Name {
            get {
                return ResourceManager.GetString("AllocationInstructionRow_ClosingQuantity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to allocation rows.
        /// </summary>
        public static string AllocationInstructionRow_Noun_Plural {
            get {
                return ResourceManager.GetString("AllocationInstructionRow_Noun_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string AllocationInstructionRow_Noun_PluralArticle {
            get {
                return ResourceManager.GetString("AllocationInstructionRow_Noun_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to allocation row.
        /// </summary>
        public static string AllocationInstructionRow_Noun_Singular {
            get {
                return ResourceManager.GetString("AllocationInstructionRow_Noun_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string AllocationInstructionRow_Noun_SingularArticle {
            get {
                return ResourceManager.GetString("AllocationInstructionRow_Noun_SingularArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify lot closure.
        /// </summary>
        public static string AllocationInstructionTable_Name {
            get {
                return ResourceManager.GetString("AllocationInstructionTable_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quantity of this transaction less closing instructions..
        /// </summary>
        public static string AllocationInstructionTable_RemainingQuantity_Description {
            get {
                return ResourceManager.GetString("AllocationInstructionTable_RemainingQuantity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining quantity.
        /// </summary>
        public static string AllocationInstructionTable_RemainingQuantity_Name {
            get {
                return ResourceManager.GetString("AllocationInstructionTable_RemainingQuantity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of the original acquisition..
        /// </summary>
        public static string BrokerTaxLot_AcquisitionDate_Description {
            get {
                return ResourceManager.GetString("BrokerTaxLot_AcquisitionDate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquisition Date.
        /// </summary>
        public static string BrokerTaxLot_AcquisitionDate_Name {
            get {
                return ResourceManager.GetString("BrokerTaxLot_AcquisitionDate_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tax lots.
        /// </summary>
        public static string BrokerTaxLot_Noun_Plural {
            get {
                return ResourceManager.GetString("BrokerTaxLot_Noun_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string BrokerTaxLot_Noun_PluralArticle {
            get {
                return ResourceManager.GetString("BrokerTaxLot_Noun_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tax lot.
        /// </summary>
        public static string BrokerTaxLot_Noun_Singular {
            get {
                return ResourceManager.GetString("BrokerTaxLot_Noun_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string BrokerTaxLot_Noun_SingularArticle {
            get {
                return ResourceManager.GetString("BrokerTaxLot_Noun_SingularArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of shares available for closing..
        /// </summary>
        public static string BrokerTaxLot_UnclosedQuantity_Description {
            get {
                return ResourceManager.GetString("BrokerTaxLot_UnclosedQuantity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available shares.
        /// </summary>
        public static string BrokerTaxLot_UnclosedQuantity_Name {
            get {
                return ResourceManager.GetString("BrokerTaxLot_UnclosedQuantity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per share cost from the original acquisition..
        /// </summary>
        public static string BrokerTaxLot_UnitCostBasis_Description {
            get {
                return ResourceManager.GetString("BrokerTaxLot_UnitCostBasis_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Cost.
        /// </summary>
        public static string BrokerTaxLot_UnitCostBasis_Name {
            get {
                return ResourceManager.GetString("BrokerTaxLot_UnitCostBasis_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal plus interest.
        /// </summary>
        public static string FutureValueResult_Balance_Description {
            get {
                return ResourceManager.GetString("FutureValueResult_Balance_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string FutureValueResult_Balance_Name {
            get {
                return ResourceManager.GetString("FutureValueResult_Balance_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of interest earned to date.
        /// </summary>
        public static string FutureValueResult_Interest_Description {
            get {
                return ResourceManager.GetString("FutureValueResult_Interest_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest.
        /// </summary>
        public static string FutureValueResult_Interest_Name {
            get {
                return ResourceManager.GetString("FutureValueResult_Interest_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date of the period.
        /// </summary>
        public static string FutureValueResult_PeriodDate_Description {
            get {
                return ResourceManager.GetString("FutureValueResult_PeriodDate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string FutureValueResult_PeriodDate_Name {
            get {
                return ResourceManager.GetString("FutureValueResult_PeriodDate_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial value plus contributions to date.
        /// </summary>
        public static string FutureValueResult_Principal_Description {
            get {
                return ResourceManager.GetString("FutureValueResult_Principal_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal.
        /// </summary>
        public static string FutureValueResult_Principal_Name {
            get {
                return ResourceManager.GetString("FutureValueResult_Principal_Name", resourceCulture);
            }
        }
    }
}
